### ISSUE TITLE
[Cloudflare Worker compatibility] loading private key of type `webcrypto.CryptoKey`

### ISSUE THREAD

**Issue by zxt-tzx** [gr2m/universal-github-app-jwt#109]
for context, I am currently using `octokit.js` and deploying to Cloudflare Workers
1. [Per this](https://developers.cloudflare.com/workers/runtime-apis/nodejs/crypto/#keys), Cloudflare Workers currently do not support the `createPrivateKey` method
2. I am trying to get around this by poly-filling the `createPrivateKey` method. Right now, if I pass the `CryptoKey` object to the constructor, it does not work

BEFORE:
```
new OctokitWithGraphQLPaginate({
  authStrategy: createAppAuth,
  auth: {
    appId,
    privateKey,
    installationId,
  },
});
```

AFTER:
```
new OctokitWithGraphQLPaginate({
  authStrategy: createAppAuth,
  auth: {
    appId,
    privateKey: await createPrivateKey(privateKeyPem);,
    installationId,
  },
});
```

Curious if you'll accept a PR on this, honestly a bit conflicted as to whether I should continue down this path or if I should try a different way of auth (e.g. instead of using GitHub App, to use a Personal Access Token or some other auth that does not require a private key). 

Advice welcome! Thanks!

**Comment by gr2m** [comment]
Oh you don't need the `createPrivateKey` method, it's only supported in Node. This library does support the native crypto module that Cloudflare workers use, you just need to convert the private key to the `PKCS#8` format first: https://github.com/gr2m/universal-github-app-jwt?tab=readme-ov-file#converting-pkcs1-to-pkcs8

But once you do that and use the private key in the new format it should just work ✨

**Comment by zxt-tzx** [comment]
Oh, if I understand you correctly, you're saying in the following, for `privateKey`, I can simply convert to `PKCS#8` format and pass the string in, in which case the `createPrivateKey` method would not be invoked?


```TS
new OctokitWithGraphQLPaginate({
  authStrategy: createAppAuth,
  auth: {
    appId,
    privateKey, // <- this
    installationId,
  },
});
```

Is that correct?

Thanks!

**Comment by gr2m** [comment]
yes that's correct.

**Comment by zxt-tzx** [comment]
thank you! closing the issue now
