### ISSUE TITLE
"module" export incompatible with Node.js

### ISSUE THREAD

**Issue by smolster** [gr2m/universal-github-app-jwt#36]
Moving [this](https://github.com/octokit/rest.js/issues/1485#issuecomment-743278408) conversation here.

**Problem**
This package's `module` export is not compatible with Node.

As such, using it in combination with Node + a web bundler (most of which prefer `module` over `main`) requires very opinionated bundler settings (e.g. specifying `mainFields` for webpack), which is suboptimal.

Could we update the package to either provide
  a) a unified distribution, or
  b) a `browser` field, and update the `module` to point to `dist-node`?

**Comment by smolster** [comment]
@gr2m opened this issue per your comments here: https://github.com/octokit/rest.js/issues/1485#issuecomment-743278408.

This is the package that led me to this issue :)

**Comment by gr2m** [comment]
ah yes, better place to discuss. 

Yeah this is the remaining package that we use in some of the `@octokit/*` modules that requires different code depending on environment

`dist-node` is cjs, not ESM, se ehttps://unpkg.com/browse/universal-github-app-jwt@1.1.0/dist-node/index.js

As mentioned in the other issue, I use `@pika/pack` which currently only provides a plugin for ESM for browsers:
https://github.com/snowpackjs/pika-pack-builders

There is no easy fix here. I think Webpack 5 is looking into aligning its implementation with the conventions from Node's ESM implementation. Last I checked it would be using the "exports" key which could have different keys: "cjs", "module", "browser", "deno". I think that's what it's going to be eventually. But changing how this package works will have a cascading effect on several widely used `@octokit/*` packages as well as `probot`. I'm not inclined to touch this now, I'm about to take break for a few weeks.

I'd recommend to fork the package and publish your fork to npm, see how it works for you and report back, it would help us deciding how we want to move forward. Once we make a decision will will replicate the setup across all the octokit/probot packages, so it's not a decision we will make easily

**Comment by smolster** [comment]
@gr2m Thanks for the thoughtful response! That all makes sense. I was able to workaround using `mainFields` in webpack for now.

Looking forward to seeing how things shake out! I'll be watching :)

Feel free to close this issue or leave it open if you'd like to use it for tracking.

**Comment by gr2m** [comment]
yeah I think we can close it in favor of https://github.com/gr2m/universal-github-app-jwt/issues/30
