### ISSUE TITLE
Deno compatibility

### ISSUE THREAD

**Issue by laughedelic** [gr2m/universal-github-app-jwt#37]
Hi! I'm trying to use this library from Deno. I tried using @octokit/app.js and @octokit/auth-app.js directly, but ran into problems. I thought this library could be a solution, but I think I'm hitting the same problem. 

Here is my code

```typescript
import { githubAppJwt } from "https://cdn.skypack.dev/universal-github-app-jwt";
import { request } from "https://cdn.skypack.dev/@octokit/request";

const appId = 123456;
const installationId = 12345678;
const privateKey = await Deno.readTextFile("private-key-pkcs8.key");

const { token } = await githubAppJwt({
  id: appId,
  privateKey: privateKey,
});

const { data } = await request(
  `POST /app/installations/${installationId}/access_tokens`,
  {
    headers: { authorization: `bearer ${token}` },
  }
);
console.log(data);
```

Here's how I run it:

```shell
►  deno run --allow-net --allow-read app-token.ts
error: Uncaught (in promise) TypeError: Cannot read property 'importKey' of undefined
  const importedKey = await crypto.subtle.importKey("pkcs8", privateKeyDER, algorithm, false, ["sign"]);
                                          ^
    at getToken (https://cdn.skypack.dev/-/universal-github-app-jwt@v1.1.0-TxlnEhpSPAyjsOdxoA3m/dist=es2020,mode=imports/optimized/universal-github-app-jwt.js:42:43)
    at githubAppJwt (https://cdn.skypack.dev/-/universal-github-app-jwt@v1.1.0-TxlnEhpSPAyjsOdxoA3m/dist=es2020,mode=imports/optimized/universal-github-app-jwt.js:57:23)
```

I know that the crypto API in Deno is a [WIP](https://github.com/denoland/deno/issues/1891), but I was hoping that there might be some workarounds for that.

If not with this library, is there any other way to authenticate a GitHub app and use Octokit libraries from Deno?

**Comment by gr2m** [comment]
I don’t know of there is a way right now, you need to create a JSON web token, is there a Deno Library for that?

once Deno has the web crypto API it should be trivial

**Comment by laughedelic** [comment]
Does this look like something that could fill the gap? https://deno.land/x/djwt

**Comment by gr2m** [comment]
Yes that looks good. I'd suggest you use that for now, until the WebCrypto API lands in Deno

**Comment by laughedelic** [comment]
Thanks for pointing me in the right direction! I made it work with that library:

```typescript
import { request } from "https://cdn.skypack.dev/@octokit/request";
import { create, getNumericDate } from "https://deno.land/x/djwt/mod.ts";

const appId = 123456;
const installationId = 12345678;
const privateKey = await Deno.readTextFile("private-key.pem")

// This is the key part:
const jwt = await create(
  { alg: "RS256", typ: "JWT" },
  {
    iss: appId.toString(), // issuer
    iat: getNumericDate(-30), // issued at time
    exp: getNumericDate(60), // expiration time 1 minute
  },
  privateKey
);

const installationAuth = await request(
  `POST /app/installations/{installationId}/access_tokens`,
  {
    headers: { authorization: "bearer " + jwt },
    installationId: installationId,
  }
);

// simple CLI:
const [method, path, json] = Deno.args;
const params = JSON.parse(json || "{}");

const requestWithAuth = request.defaults({
  headers: { authorization: "token " + installationAuth.data.token },
});
const { data } = await requestWithAuth([method, path].join(" "), params);
console.log(data);
```

**Comment by gr2m** [comment]
Glad to hear that you figure it out! I'll see if I can mention this issue in the README until we support deno

**Comment by laughedelic** [comment]
For the reference, I published this as a tiny Deno library and a CLI app for my own usage: https://deno.land/x/github_app_auth

Will be glad to deprecate it once Deno is fully supported here 🙂

**Comment by laughedelic** [comment]
I think with the release of Deno 1.14 this issue can be closed. Example from the original post now works 🎉

**Comment by gr2m** [comment]
Awesome news, thank you so much for the follow up. and the PR 💖
