### ISSUE TITLE
Webpack: incorrect build

### ISSUE THREAD

**Issue by tetchel** [gr2m/universal-github-app-jwt#38]
Hi, I am using this library through `@octokit/auth-app` in a Node enviroment

It worked until I started webpacking my project

Now, I receive this message:
```
[universal-github-app-jwt] Private Key is in PKCS#1 format, but only PKCS#8 is supported. See https://github.com/gr2m/universal-github-app-jwt#readme"
```

From the readme, I see this message is meant to only be seen in a browser environment.

It looks like this package has a `browser` field in `package.json` but no `main` or `module` field. So the `browser` export is used by webpack, and my code receives the browser version of this package instead of the correct Node (commonjs module) one.

I think this could be solved by adding a `main` field to `package.json` that points to the node build, or maybe `module`

https://github.com/webpack/webpack/issues/4674

**Comment by tetchel** [comment]
I can see in my webpacked js file it is using `./node_modules/universal-github-app-jwt/dist-web/index.js`

**Comment by tetchel** [comment]
hold on, the `package.json` in my node_modules does not match the one in this repository. it has a `main` and module`. It looks like webpack is using the `module` field instead of the `main`...

**Comment by tetchel** [comment]
I was able to work around this using https://github.com/webpack/webpack/issues/5756#issuecomment-405468106

I'm not sure if this is a problem with this library or with webpack itself. Hopefully I don't have any other dependencies that will fall over due to me using `main` before `module`.

**Comment by gr2m** [comment]
it's all related to modules & node. I'll most lively rewrite this library as native ESM soon

**Comment by tetchel** [comment]
yea, just another day in javascript modules.

**Comment by gr2m** [comment]
it's going to be lots of friction in Node land for a year or two, but I'm convinced it's going to be worth it

**Comment by tetchel** [comment]
anyway, you can close this issue if there's no immediate action to take.

**Comment by gr2m** [comment]
others will run into this problem, let's leave it open if you don't mind

**Comment by PendletonJones** [comment]
For others using the `@nrwl/node` builder you will need to use a custom webpack config with the following contents: 

```js
module.exports = (config) => {
    config.resolve.mainFields = ['main', 'module'];
    return config;
};
```

**Comment by ranmocy** [comment]
According to the latest release `1.1.0`'s `package.json` file, only `main` field references `dist-node/index.js` build.

So the webpack config you actually need is:
```js
result.resolve.mainFields = ['main']
```

**Comment by gr2m** [comment]
This should be resolved the latest version. Please create a new issue if the problems persists with v2+
