### ISSUE TITLE
Module field points to browser-only variant

### ISSUE THREAD

**Issue by devversion** [gr2m/universal-github-app-jwt#61]
This package is often transitively included as part of octokit/app-auth. For teams bundling e.g. GitHub action code into a single file using ESBuild with `platform: node` and prioritizing ESM inputs through `module`, then `main`- this means that the bundled output breaks due to the browser-specific code being bundled from `universal-github-app-jwt`.

ESBuild itself points out that library authors should have browser-specific code in the `browser` package.json field, compared to the defacto-standard, generic ESM `module` field. Is there any way this could be updated?

**Comment by gr2m** [comment]
would it help if I turned the package into a native ES Module and used conditional exports? It's only a matter of time, I can as well do it today

**Comment by devversion** [comment]
Yes, that would certainly help a lot, especially for esbuild. Let me know if I can help, although it seems like a `pika` issue?

**Comment by devversion** [comment]
oh yeah, this sounds like a larger update. I'm not quite sure yet how much the fix would help in the ecosystem together with e.g. `@octokit/app-auth` et al. Maybe this repo is a good start.

Would you want me to (just checking to set the goals clearly & if I could spend some time on it)

1. Switch the full repo to ESM with package exports (removing pika building)
2. Optional: Maybe remove TS in favor of a simple `d.ts` along with `.js`?
3. Replace Jest with Ava to run tests in ESM simpler?

**Comment by gr2m** [comment]
> I'm not quite sure yet how much the fix would help in the ecosystem together with e.g. `@octokit/app-auth` et al

that won't help unfortunately until we implement it in https://github.com/octokit/octokit-next.js. `@octokit/app-auth` will continue to use the current version of `universal-github-app-jwt` because it won't be able to import the ESM version.

> Would you want me to (just checking to set the goals clearly & if I could spend some time on it)
> 
> 1. Switch the full repo to ESM with package exports (removing pika building)
> 2. Optional: Maybe remove TS in favor of a simple `d.ts` along with `.js`?
> 3. Replace Jest with Ava to run tests in ESM simpler?

Only the first point is a breaking step. I'd definitely like to do the two others shortly after. But we can split it up in multiple pull requests if that's easier

There are other packages outside of the `@octokit/*` scope that I migrated already, such as https://github.com/gr2m/before-after-hook and https://github.com/gr2m/universal-user-agent. This package is somewhat up next.

**Comment by gr2m** [comment]
This should be resolved via https://github.com/gr2m/universal-github-app-jwt/pull/65. I can get the correct builds with `esbuild` by using `--platform node` for Node and `--platform neutral` for everything else.

See release notes for v2 at https://github.com/gr2m/universal-github-app-jwt/releases/tag/v2.0.0

**Comment by devversion** [comment]
Thanks @gr2m- sorry I couldn't help here. I still had it bookmarked in my mails but got dragged into various other Q4 work
