### ISSUE TITLE
Typescript issue using v2

### ISSUE THREAD

**Issue by friesenA** [gr2m/universal-github-app-jwt#67]
Hi!. I'm hoping to upgrade this libraries use in octokit/auth-app from v1.0.1 to v2.0.1. Thanks for the vulnerability patch!

Having some issues with the package transformation in v1 -> v2. When running tests Jest is unable to parse the index.js file.
```
    import { getToken } from "#get-token";
    ^^^^^^
    SyntaxError: Cannot use import statement outside a module
```
[import line reference](https://github.com/gr2m/universal-github-app-jwt/blob/master/index.js#L4)

Are there additional modifications needed beyond the default export to support the ESM change in a typescript project?

**Comment by gr2m** [comment]
Hmm it should just work from what I know. Please share if you find out what the problem was, I hope you figure it out quickly

**Comment by wolfy1339** [comment]
What setting are you using for `moduleResolution`?

According to the [TypeScript docs](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing), it should work

Also, the patch was backported in [`v1.1.1`](https://github.com/gr2m/universal-github-app-jwt/releases/tag/v1.1.1) of this package

**Comment by gr2m** [comment]
closing due to inactivty
