### ISSUE TITLE
The requested module '#crypto' does not provide an export named 'subtle'

### ISSUE THREAD

**Issue by melroyvandenberg** [gr2m/universal-github-app-jwt#76]
The package seems to be broken now with the introducing of this `#crypto` import. I'm using v2.0.5 now of the package. And using `universal-github-app-jwt` directly, which gives me:

```
The requested module '#crypto' does not provide an export named 'subtle'
```

![image](https://github.com/gr2m/universal-github-app-jwt/assets/66132222/6d78648c-e98f-4083-959f-b134c9e3b303)

Usage example:

```js
import githubAppJwt from "universal-github-app-jwt"

const { token, appId, expiration } = await githubAppJwt({ id: APP_ID, privateKey: PRIVATE_KEY })
```

Help..

**Comment by gr2m** [comment]
If you use it directly, what node version are you using? Do you do any bundling? I would need a reproducible test case that does not involve AWS in order to look into it

**Comment by gr2m** [comment]
closing due to inactivy

**Comment by groboclown** [comment]
I was able to reproduce this issue.  Using `docker`, this Dockerfile will generate the error message.

```Dockerfile
FROM ubuntu:latest

RUN apt-get update && apt-get install -y npm=8.5.1~ds-1 nodejs=12.22.9~dfsg-1ubuntu3.1
RUN mkdir /work \
    && cd /work \
    && echo '{ "type": "module" }' > package.json \
    && npm install universal-github-app-jwt \
    && echo 'import githubAppJwt from "universal-github-app-jwt"' > v.js \
    && node v.js
```

**Comment by gr2m** [comment]
> `nodejs=12.22.9` 

Node 12 is no longer maintained, for a very long time, and it's not supported by this module.

**Comment by TechQuery** [comment]
@gr2m The same error thrown in `2.2.0` with Deno runtime recently:
https://github.com/Yuyz0112/dewhale/actions/runs/9043026122/job/24850220873#step:4:273

**Comment by gr2m** [comment]
Can you file a new issue please? I'd appreciate help investigating

**Comment by TechQuery** [comment]
> Can you file a new issue please? I'd appreciate help investigating

@gr2m Thanks, but I have no idea about how to describe this issue, and my upstream just fix this bug by pinning a package's version: Yuyz0112/dewhale@2445b94

**Comment by gr2m** [comment]
if you or @Yuyz0112 could create a minimal reproducible test case of the problem using `universal-github-app-jwt` directly, I'd be happy to look into it
